Repository ttukttak3/ttukttak, pull requests merged in 2022-06, with the labels that each got.

#5 GlobalExceptionHandler, BaseTimeEntity 추가
  server/build.gradle
  server/src/main/java/com/ttukttak/common/BaseTimeEntity.java
  server/src/main/java/com/ttukttak/common/config/UtilConfig.java
  server/src/main/java/com/ttukttak/common/dto/PageResponse.java
  server/src/main/java/com/ttukttak/common/dto/StatusMessage.java
  server/src/main/java/com/ttukttak/common/exception/ExceptionFactory.java
  server/src/main/java/com/ttukttak/common/exception/GlobalExceptionHandler.java
  server/src/main/java/com/ttukttak/common/exception/StatusCode.java
Labels: backend

#6 Feat: [BE]Common AWSConfig, StorageUploader, FileUploadResponse, depe…
  server/build.gradle
  server/src/main/java/com/ttukttak/common/StorageUploader.java
  server/src/main/java/com/ttukttak/common/config/AWSConfig.java
  server/src/main/java/com/ttukttak/common/dto/FileUploadResponse.java
  server/src/main/resources/application.yml
Labels: backend

#8 [FE] 공통 컴포넌트 및 프로필쪽 수정
  front/package.json
  front/src/app/headerSlice.js
  front/src/app/store.js
  front/src/app/urlSlice.js
  front/src/assets/img/logo/Croods_The_Feedback.png
  front/src/assets/img/logo/kakao_logo.png
  front/src/components/Button/Button.jsx
  front/src/components/Button/Button.style.jsx
  front/src/components/layout/Footer.jsx
  front/src/components/layout/Footer.style.jsx
  front/src/components/layout/Header.jsx
  front/src/components/layout/Header.style.jsx
  front/src/components/layout/Layout.jsx
  front/src/pages/Home/HomePage.jsx
  front/src/pages/OauthLogin/Login/LoginPage.jsx
  front/src/pages/OauthLogin/Login/LoginPage.style.jsx
  front/src/pages/OauthLogin/Oauth/Auth.jsx
  front/src/pages/OauthLogin/Profile/ProfilePage.jsx
  front/src/pages/OauthLogin/Profile/ProfilePage.style.jsx
  front/src/styles/GlobalStyle.jsx
  front/src/styles/theme.js
  front/src/util/OauthApi.jsx
Labels: frontend

#7 [BE] 채팅기능 초기 구현
  server/build.gradle
  server/src/main/java/com/ttukttak/book/entity/Book.java
  server/src/main/java/com/ttukttak/book/repository/BookRepository.java
  server/src/main/java/com/ttukttak/chat/config/EmbeddedRedisConfig.java
  server/src/main/java/com/ttukttak/chat/config/RedisConfig.java
  server/src/main/java/com/ttukttak/chat/config/WebSocketConfig.java
  server/src/main/java/com/ttukttak/chat/controller/ChatMessageController.java
  server/src/main/java/com/ttukttak/chat/controller/ChatRoomController.java
  server/src/main/java/com/ttukttak/chat/controller/WebSocketController.java
  server/src/main/java/com/ttukttak/chat/dto/ChatMessageDto.java
  server/src/main/java/com/ttukttak/chat/dto/ChatRoomCard.java
  server/src/main/java/com/ttukttak/chat/dto/ChatRoomInfo.java
  server/src/main/java/com/ttukttak/chat/dto/ChatRoomRequest.java
  server/src/main/java/com/ttukttak/chat/dto/ChatUser.java
  server/src/main/java/com/ttukttak/chat/dto/LastMessage.java
  server/src/main/java/com/ttukttak/chat/dto/MessageType.java
  server/src/main/java/com/ttukttak/chat/entity/ChatMessage.java
  server/src/main/java/com/ttukttak/chat/entity/ChatRoom.java
  server/src/main/java/com/ttukttak/chat/entity/LastCheckedMessage.java
  server/src/main/java/com/ttukttak/chat/repository/ChatMessageRepository.java
  server/src/main/java/com/ttukttak/chat/repository/ChatRoomRepository.java
  server/src/main/java/com/ttukttak/chat/repository/ChatRoomRepositoryCustom.java
  server/src/main/java/com/ttukttak/chat/repository/LastCheckedMessageRepository.java
  server/src/main/java/com/ttukttak/chat/service/ChatMessageService.java
  server/src/main/java/com/ttukttak/chat/service/ChatMessageServiceImpl.java
  server/src/main/java/com/ttukttak/chat/service/ChatRoomService.java
  server/src/main/java/com/ttukttak/chat/service/ChatRoomServiceImpl.java
  server/src/main/java/com/ttukttak/chat/service/RedisPublisher.java
  server/src/main/java/com/ttukttak/chat/service/RedisSubscriber.java
  server/src/main/java/com/ttukttak/common/config/QuerydslConfig.java
  server/src/main/java/com/ttukttak/oauth/entity/User.java
  server/src/test/java/com/ttukttak/chat/CascadeTest.java
Labels: backend

#12 [BE] 회원가입 로직 추가 및 소스 수정
  server/src/main/java/com/ttukttak/TtukttakApplication.java
  server/src/main/java/com/ttukttak/oauth/controller/UserController.java
  server/src/main/java/com/ttukttak/oauth/dto/SignUpRequest.java
  server/src/main/java/com/ttukttak/oauth/dto/UserDto.java
  server/src/main/java/com/ttukttak/oauth/entity/User.java
  server/src/main/java/com/ttukttak/oauth/entity/UserPrincipal.java
  server/src/main/java/com/ttukttak/oauth/repository/UserRepository.java
  server/src/main/java/com/ttukttak/oauth/service/CustomOAuth2UserService.java
  server/src/main/java/com/ttukttak/oauth/service/CustomUserDetailService.java
  server/src/main/java/com/ttukttak/oauth/service/UserService.java
  server/src/main/java/com/ttukttak/oauth/service/UserServiceImpl.java
  server/src/main/java/com/ttukttak/oauth/token/TokenAuthenticationFilter.java
Labels: backend

#13 [FE] 프로필 작업 및 모달 팝업 작업
  front/package.json
  front/public/index.html
  front/src/App.jsx
  front/src/components/Modal/SelectPopupB.jsx
  front/src/components/Modal/SelectPopupB.style.jsx
  front/src/pages/OauthLogin/Login/LoginPage.jsx
  front/src/pages/OauthLogin/Profile/ProfilePage.jsx
  front/src/pages/OauthLogin/Profile/ProfilePage.style.jsx
  front/src/pages/OauthLogin/Profile/validate.jsx
  front/src/util/OauthApi.jsx
Labels: frontend

#15 [FE] 채팅 기능 api 변경
  front/src/app/store.js
  front/src/app/userSlice.js
  front/src/components/layout/Layout.jsx
  front/src/pages/Chat/ChatItem/ChatBookInfo.jsx
  front/src/pages/Chat/ChatItem/ChatBookInfo.style.jsx
  front/src/pages/Chat/ChatItem/ChatFooter.jsx
  front/src/pages/Chat/ChatItem/ChatFooter.style.jsx
  front/src/pages/Chat/ChatItem/ChatItemPage.jsx
  front/src/pages/Chat/ChatList/ChatListItem.style.jsx
  front/src/pages/Chat/ChatList/ChatPage.jsx
  front/src/pages/Login/loginSlice.js
  front/src/pages/UploadBook/UploadBookPage.jsx
  front/src/pages/UploadBook/UploadBookPage.style.jsx
  front/src/util/ChatSocketApi.jsx
  front/src/util/MessageApi.jsx
Labels: frontend

#19 [BE] toEntity 제거 및 어노테이션 제거
  server/src/main/java/com/ttukttak/TtukttakApplication.java
  server/src/main/java/com/ttukttak/oauth/service/UserServiceImpl.java
Labels: backend

#20 [FE] error : eslint error 수정
  front/src/pages/Chat/ChatItem/ChatItemPage.jsx
  front/src/pages/Chat/ChatList/ChatPage.jsx
  front/src/pages/UploadBook/UploadBookPage.jsx
  front/src/util/MessageApi.jsx
Labels: frontend

#22 [BE] saveChatMessage toEntity -> of로 변경
  server/src/main/java/com/ttukttak/chat/service/ChatMessageServiceImpl.java
Labels: backend

#24 feat:eslint 빌드 오류 수정
  front/src/pages/OauthLogin/Oauth/Auth.jsx
Labels: frontend

#21 Security 허용 URL 설정 변경
  server/src/main/java/com/ttukttak/common/config/SecurityConfig.java
Labels: backend

#25 [BE]: 채팅API URI 변경, ModelMapper Converter 추가
  server/src/main/java/com/ttukttak/chat/controller/ChatMessageController.java
  server/src/main/java/com/ttukttak/chat/controller/ChatRoomController.java
  server/src/main/java/com/ttukttak/chat/entity/ChatMessage.java
  server/src/main/java/com/ttukttak/chat/entity/ChatRoom.java
  server/src/main/java/com/ttukttak/chat/repository/ChatRoomRepository.java
  server/src/main/java/com/ttukttak/chat/repository/ChatRoomRepositoryCustom.java
  server/src/main/java/com/ttukttak/chat/repository/ChatRoomRepositoryImpl.java
  server/src/main/java/com/ttukttak/chat/service/ChatRoomServiceImpl.java
  server/src/main/java/com/ttukttak/common/config/TestConfig.java
  server/src/main/java/com/ttukttak/common/config/UtilConfig.java
  server/src/test/java/com/ttukttak/chat/CascadeTest.java
  server/src/test/java/com/ttukttak/chat/ChatMessageTest.java
  server/src/test/java/com/ttukttak/chat/MappingTest.java
Labels: backend

#26 [BE] User 연관관계 추가 및 회원가입 반환값 수정
  server/src/main/java/com/ttukttak/oauth/controller/UserController.java
  server/src/main/java/com/ttukttak/oauth/dto/SignUpRequest.java
  server/src/main/java/com/ttukttak/oauth/dto/UserDto.java
  server/src/main/java/com/ttukttak/oauth/entity/User.java
  server/src/main/java/com/ttukttak/oauth/repository/UserRepository.java
  server/src/main/java/com/ttukttak/oauth/service/UserService.java
  server/src/main/java/com/ttukttak/oauth/service/UserServiceImpl.java
  server/src/main/java/com/ttukttak/oauth/token/TokenProvider.java
Labels: backend

#27 [BE] HomeTown Entity 수정, DTO 추가, Request Swagger 추가
  server/src/main/java/com/ttukttak/address/controller/AddressController.java
  server/src/main/java/com/ttukttak/address/dto/CoordinateRequest.java
  server/src/main/java/com/ttukttak/address/dto/HomeTownDto.java
  server/src/main/java/com/ttukttak/address/entity/HomeTown.java
  server/src/main/java/com/ttukttak/address/service/HomeTownServiceImpl.java
Labels: backend

#28 [BE]Security JWT 토큰 검증 추가
  server/src/main/java/com/ttukttak/common/config/SecurityConfig.java
  server/src/main/java/com/ttukttak/oauth/token/JwtAuthenticationEntryPoint.java
Labels: backend

#30 [FE] json-server도입
  front/package.json
  front/server/data.json
  front/server/index.js
  front/src/pages/Chat/ChatList/ChatPage.jsx
  front/src/util/MessageApi.jsx
Labels: frontend

#32 [FE] book upload page modal 추가
  front/public/favicon.ico
  front/public/index.html
  front/public/logo192.png
  front/public/logo2.png
  front/public/logo512.png
  front/public/manifest.json
  front/src/components/Modal/SelectPopupBottom.jsx
  front/src/pages/OauthLogin/Profile/ProfilePage.jsx
  front/src/pages/UploadBook/PutBookInfoByUser.jsx
  front/src/pages/UploadBook/UploadBookPage.jsx
Labels: frontend

#34 [FE] Home 작업 추가
  front/src/assets/img/userInterFace/gradation.png
  front/src/assets/img/userInterFace/local_library.png
  front/src/assets/img/userInterFace/star.png
  front/src/components/layout/Header.jsx
  front/src/components/layout/Header.style.jsx
  front/src/components/layout/Layout.jsx
  front/src/components/layout/Layout.style.jsx
  front/src/pages/Home/BookOnLoanPage.jsx
  front/src/pages/Home/HomePage.jsx
  front/src/pages/Home/HomePage.style.jsx
  front/src/pages/OauthLogin/Profile/ProfilePage.jsx
  front/src/util/OauthApi.jsx
Labels: frontend

#35 [BE]: TestConfig, QuerydslConfig Bean 중복이슈 대응
  server/src/main/java/com/ttukttak/common/config/TestConfig.java
  server/src/test/java/com/ttukttak/chat/CascadeTest.java
  server/src/test/java/com/ttukttak/chat/ChatMessageTest.java
  server/src/test/java/com/ttukttak/chat/MappingTest.java
Labels: bug
